/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.dormitory;

import businesslogic.EcoSystem;
import businesslogic.dormitory.LoginDetails;
import static businesslogic.dormitory.LoginDetails.AdminDetails;
import businesslogic.dormitory.FeesPaymentHistory;
import businesslogic.dormitory.RoomBookingHistory;
import businesslogic.dormitory.SalaryPaymentHistory;
import java.util.Set;
import javax.swing.JOptionPane;

/**
 *
 * @author Hinal
 */
public class EmpLoginPage extends javax.swing.JPanel {

    /**
     * Creates new form EmpLoginPage
     */
    LoginDetails EmployeeDetails;
    LoginDetails StudentDetails;
    FeesPaymentHistory history;
    SalaryPaymentHistory historysal;
    RoomBookingHistory historyroom;
    
    private EcoSystem ecoSystem;
//    RoomBookingHistory historyroom;
    public EmpLoginPage(LoginDetails EmployeeDetails,FeesPaymentHistory history,LoginDetails StudentDetails, SalaryPaymentHistory historysal,RoomBookingHistory historyroom) {
        initComponents();
        this.EmployeeDetails = EmployeeDetails;
        this.StudentDetails = StudentDetails;
        this.history = history;
        this.historysal = historysal;
        this.historyroom = historyroom;
        btnCreateStudent.setVisible(false);
        btnAddRoom.setVisible(false);
        btnViewVitals.setVisible(false);
        btnEncounterHistorySal.setVisible(false);
        btnViewRoomDetails.setVisible(false);
        
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EmployeeSplitPane = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        btnLogin = new javax.swing.JButton();
        lblUsername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnAddRoom = new javax.swing.JButton();
        btnCreateStudent = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();
        btnViewVitals = new javax.swing.JButton();
        btnEncounterHistorySal = new javax.swing.JButton();
        btnViewRoomDetails = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();

        EmployeeSplitPane.setBackground(new java.awt.Color(204, 255, 204));
        EmployeeSplitPane.setDividerLocation(250);
        EmployeeSplitPane.setDividerSize(0);
        EmployeeSplitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        lblUsername.setText("Username:");

        lblPassword.setText("Password:");

        txtUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUsernameKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Employee Login");

        btnAddRoom.setText("Add Room");
        btnAddRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddRoomActionPerformed(evt);
            }
        });

        btnCreateStudent.setText("Create Student");
        btnCreateStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateStudentActionPerformed(evt);
            }
        });

        btnViewVitals.setText("View Fees Details");
        btnViewVitals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewVitalsActionPerformed(evt);
            }
        });

        btnEncounterHistorySal.setText("View Salary Details");
        btnEncounterHistorySal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncounterHistorySalActionPerformed(evt);
            }
        });

        btnViewRoomDetails.setText("View Room Details");
        btnViewRoomDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewRoomDetailsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(161, 161, 161)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnViewRoomDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViewVitals, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEncounterHistorySal, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                    .addComponent(btnCreateStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAddRoom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(370, 370, 370))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtPassword, txtUsername});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAddRoom)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCreateStudent)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnViewVitals)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEncounterHistorySal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnViewRoomDetails))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnLogin)))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        EmployeeSplitPane.setTopComponent(jPanel1);

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 561, Short.MAX_VALUE)
        );

        EmployeeSplitPane.setRightComponent(jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EmployeeSplitPane)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EmployeeSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 833, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        Set<String> Keys = EmployeeDetails.EmployeeKeys();
        String Username = txtUsername.getText();
        String Password = txtPassword.getText();
        for(String key: Keys){
            if(Username.equals(key)){
                if(Password.equals(EmployeeDetails.getEmployeeValue(key))){
                    btnCreateStudent.setVisible(true);
                    btnAddRoom.setVisible(true);
                    btnViewVitals.setVisible(true);
                    btnEncounterHistorySal.setVisible(true);
                    btnViewRoomDetails.setVisible(true);

                }
            }
        }

        /*Set<String> Keys = this.StudentDetailsinStudentInitial.keys();
        String UserName = txtUsername.getText();
        String Password = txtPassword.getText();

        for(String key: Keys){
            if(UserName.equals(key)){
                if(Password.equals(StudentDetailsinStudentInitial.getValue(key))){
                    StudentAfterLogin UserLogin = new StudentAfterLogin();
                    StudentSplitPane.setRightComponent(UserLogin);
                    txtLoggedPerson.setText(key);
                    lblLogged.setVisible(true);
                    txtLoggedPerson.setVisible(true);
                    btnBookAppointment.setVisible(true);
                    btnEncounterHistory.setVisible(true);
                    btnPersonalDetails.setVisible(true);

                }
            }

        }*/
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnAddRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddRoomActionPerformed
        // TODO add your handling code here:
        AddRoom AddRoom = new AddRoom(historyroom);
        EmployeeSplitPane.setRightComponent(AddRoom);
    }//GEN-LAST:event_btnAddRoomActionPerformed

    private void btnCreateStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateStudentActionPerformed
        // TODO add your handling code here:
        StudCreate EmployeeStudentCreate = new StudCreate(StudentDetails);
        EmployeeSplitPane.setRightComponent(EmployeeStudentCreate);
    }//GEN-LAST:event_btnCreateStudentActionPerformed

    private void btnViewVitalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewVitalsActionPerformed
        // TODO add your handling code here:
        ViewFeesDetails viewFeesDetails = new ViewFeesDetails(history);
        EmployeeSplitPane.setRightComponent(viewFeesDetails);
        
    }//GEN-LAST:event_btnViewVitalsActionPerformed

    private void txtUsernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsernameKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
	if(Character.isLetterOrDigit(c)|| Character.isISOControl(c))
    {
        txtUsername.setEditable(true);
    }
    else
    {
        txtUsername.setEditable(false);
        JOptionPane.showMessageDialog(this, "Invalid Input \nenter valid username");
    }
    }//GEN-LAST:event_txtUsernameKeyPressed

    private void btnEncounterHistorySalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncounterHistorySalActionPerformed
        // TODO add your handling code here:
        ViewSalaryDetails viewSalaryDetails = new ViewSalaryDetails(historysal);
        EmployeeSplitPane.setRightComponent(viewSalaryDetails);

    }//GEN-LAST:event_btnEncounterHistorySalActionPerformed

    private void btnViewRoomDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewRoomDetailsActionPerformed
        // TODO add your handling code here:
        ViewRoomDetails viewRoom = new ViewRoomDetails(historyroom);
        EmployeeSplitPane.setRightComponent(viewRoom);
    }//GEN-LAST:event_btnViewRoomDetailsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane EmployeeSplitPane;
    private javax.swing.JButton btnAddRoom;
    private javax.swing.JButton btnCreateStudent;
    private javax.swing.JButton btnEncounterHistorySal;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnViewRoomDetails;
    private javax.swing.JButton btnViewVitals;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

    
}
