/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI.dormitory;
import businesslogic.DB4OUtil.DB4OUtil;
import businesslogic.EcoSystem;


import businesslogic.dormitory.LoginDetails;
import businesslogic.dormitory.FeesPaymentHistory;
import businesslogic.dormitory.SalaryPaymentHistory;
import businesslogic.dormitory.RoomBookingHistory;
import businesslogic.dormitory.FeesPayment;

/**
 *
 * @author Hinal
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    private EcoSystem ecoSystem;
    private DB4OUtil db4OUtil = DB4OUtil.getInstance();

    LoginDetails StudentDetailsinMain;
    LoginDetails AdminDetailsMain;
    LoginDetails EmployeeDetails;
    LoginDetails HospitalAdminDetails;
    LoginDetails CommunityAdminDetails;
    FeesPaymentHistory history;
    SalaryPaymentHistory historysal;
    RoomBookingHistory historyroom;
    FeesPaymentHistory feesPaymentHistory;
    RoomBookingHistory roomBookingHistory;
    SalaryPaymentHistory salaryPaymentHistory;
    LoginDetails loginDetails;
    
    
    private static int flag = 0;
   
    
    public MainJFrame() {
        initComponents();
        if(flag == 0){
        ecoSystem = db4OUtil.retrieveSystem();
        if(ecoSystem.getFeesPaymentHistory() != null) {
                this.feesPaymentHistory = ecoSystem.getFeesPaymentHistory();
            } else {
                this.feesPaymentHistory = new FeesPaymentHistory();
            }
        if(ecoSystem.getRoomBookingHistory() != null) {
                this.roomBookingHistory = ecoSystem.getRoomBookingHistory();    
            } else{
                this.roomBookingHistory = new RoomBookingHistory();
            }
        if(ecoSystem.getSalaryPaymentHistory() != null) {
                this.salaryPaymentHistory = ecoSystem.getSalaryPaymentHistory();
            } else {
                this.salaryPaymentHistory = new SalaryPaymentHistory();
            }
        if(ecoSystem.getLoginDetails() != null) {
                this.loginDetails = ecoSystem.getLoginDetails();
            } else {
                this.loginDetails = new LoginDetails();
            }
        
            
        }
        flag++;
        
       
       
        StudentDetailsinMain = new LoginDetails();
        AdminDetailsMain = new LoginDetails();
        EmployeeDetails = new LoginDetails();
        HospitalAdminDetails = new LoginDetails();
        CommunityAdminDetails = new LoginDetails();
        history = new FeesPaymentHistory();
        historysal = new SalaryPaymentHistory();
        historyroom = new RoomBookingHistory();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainSplitPane = new javax.swing.JSplitPane();
        RoleSelectionPane = new javax.swing.JPanel();
        btnSystemAdmin = new javax.swing.JButton();
        btnEmployee = new javax.swing.JButton();
        btnStudent = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainSplitPane.setDividerLocation(500);

        RoleSelectionPane.setBackground(new java.awt.Color(204, 255, 204));

        btnSystemAdmin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSystemAdmin.setText("System Admin");
        btnSystemAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSystemAdminActionPerformed(evt);
            }
        });

        btnEmployee.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEmployee.setText("Employee Login");
        btnEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmployeeActionPerformed(evt);
            }
        });

        btnStudent.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnStudent.setText("Student Login");
        btnStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RoleSelectionPaneLayout = new javax.swing.GroupLayout(RoleSelectionPane);
        RoleSelectionPane.setLayout(RoleSelectionPaneLayout);
        RoleSelectionPaneLayout.setHorizontalGroup(
            RoleSelectionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RoleSelectionPaneLayout.createSequentialGroup()
                .addContainerGap(326, Short.MAX_VALUE)
                .addGroup(RoleSelectionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnStudent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(RoleSelectionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnEmployee, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                        .addComponent(btnSystemAdmin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(17, 17, 17))
        );
        RoleSelectionPaneLayout.setVerticalGroup(
            RoleSelectionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RoleSelectionPaneLayout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addComponent(btnSystemAdmin)
                .addGap(27, 27, 27)
                .addComponent(btnStudent)
                .addGap(26, 26, 26)
                .addComponent(btnEmployee)
                .addContainerGap(670, Short.MAX_VALUE))
        );

        MainSplitPane.setLeftComponent(RoleSelectionPane);

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 495, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );

        MainSplitPane.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainSplitPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainSplitPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmployeeActionPerformed
        // TODO add your handling code here:
        EmpLoginPage EmployeeFirstPage = new EmpLoginPage(EmployeeDetails,history,StudentDetailsinMain,historysal,historyroom);
        MainSplitPane.setRightComponent(EmployeeFirstPage);
    }//GEN-LAST:event_btnEmployeeActionPerformed

    private void btnStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentActionPerformed
        // TODO add your handling code here:
        StudentInitialPage StudentFirstPage = new StudentInitialPage(this.StudentDetailsinMain,history);
        MainSplitPane.setRightComponent(StudentFirstPage);
    }//GEN-LAST:event_btnStudentActionPerformed

    private void btnSystemAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSystemAdminActionPerformed
        // TODO add your handling code here:AdminDetailsMain
        SystemAdminLoginPage AdminLogin = new SystemAdminLoginPage(AdminDetailsMain,EmployeeDetails,HospitalAdminDetails,CommunityAdminDetails,history,StudentDetailsinMain,historysal, historyroom);
        MainSplitPane.setRightComponent(AdminLogin);
    }//GEN-LAST:event_btnSystemAdminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane MainSplitPane;
    private javax.swing.JPanel RoleSelectionPane;
    private javax.swing.JButton btnEmployee;
    private javax.swing.JButton btnStudent;
    private javax.swing.JButton btnSystemAdmin;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
