/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.UniversityManagement;

import businesslogic.EcoSystem;
import businesslogic.PersonU;
import businesslogic.UniversityManagement.Course;
import businesslogic.UniversityManagement.CourseAssignment;
import businesslogic.UniversityManagement.PlacementCoordinator;
import businesslogic.UniversityManagement.Professor;
import businesslogic.UniversityManagement.Student;
import ui.school.SchoolAdminRole.*;
import java.awt.CardLayout;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JSplitPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import ui.MainJFrame;

/**
 *
 * @author drashtibhingradiya
 */
public class ProfessorDashboard extends javax.swing.JPanel {

    /**
     * Creates new form DashboardJPanel
     */
   private EcoSystem ecoSystem;
   private Professor person;
    
    public ProfessorDashboard(EcoSystem ecoSystem, Professor person) {
        initComponents();
        this.ecoSystem = ecoSystem;
        this.person = person;
        setSize(1060, 770);
        workAreaPanel.setVisible(true);
        gradesPanel.setVisible(false);
        coursesPanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DashboardPanel = new javax.swing.JSplitPane();
        leftPane = new javax.swing.JPanel();
        btnGrades = new javax.swing.JButton();
        btnCourses = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        rightPane = new javax.swing.JLayeredPane();
        workAreaPanel = new javax.swing.JPanel();
        workAreaPane = new javax.swing.JLabel();
        gradesPanel = new javax.swing.JPanel();
        studentSplitPane1 = new javax.swing.JSplitPane();
        navigateBackPanel1 = new javax.swing.JPanel();
        btnBackTranscript = new javax.swing.JButton();
        btnLogoutTranscript = new javax.swing.JButton();
        lblManageGrades = new javax.swing.JLabel();
        studentWorkAreaPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCourseAssignments = new javax.swing.JTable();
        txtStudentFirstName = new javax.swing.JTextField();
        txtCourseName = new javax.swing.JTextField();
        lblCourseID = new javax.swing.JLabel();
        lblCourseName = new javax.swing.JLabel();
        txtGrade = new javax.swing.JTextField();
        lblGrade = new javax.swing.JLabel();
        txtStudentIDTranscript = new javax.swing.JTextField();
        lblCurrentSemester1 = new javax.swing.JLabel();
        lblStudentIDTranscript = new javax.swing.JLabel();
        comboSemester1 = new javax.swing.JComboBox<>();
        btnUpdateGrade = new javax.swing.JButton();
        lblStudentFirstName = new javax.swing.JLabel();
        txtCourseID = new javax.swing.JTextField();
        btnViewGrade = new javax.swing.JButton();
        lblCourseDescription = new javax.swing.JLabel();
        txtCourseDescription = new javax.swing.JTextField();
        coursesPanel = new javax.swing.JPanel();
        studentSplitPane2 = new javax.swing.JSplitPane();
        navigateBackPanel2 = new javax.swing.JPanel();
        btnBackTranscript1 = new javax.swing.JButton();
        btnLogoutTranscript1 = new javax.swing.JButton();
        lblCourseManagement = new javax.swing.JLabel();
        studentWorkAreaPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblTranscripts1 = new javax.swing.JTable();
        txtCourseName1 = new javax.swing.JTextField();
        txtCourseID1 = new javax.swing.JTextField();
        lblCourseName1 = new javax.swing.JLabel();
        lblCourseID1 = new javax.swing.JLabel();
        lblCourseDay1 = new javax.swing.JLabel();
        txtDescription1 = new javax.swing.JTextField();
        lblProfIDCourse = new javax.swing.JLabel();
        lblCourseTime1 = new javax.swing.JLabel();
        txtMajorCourse = new javax.swing.JTextField();
        lblMajorCourse = new javax.swing.JLabel();
        lblDegreeLevelCourse = new javax.swing.JLabel();
        lblCurrentSemesterCourse = new javax.swing.JLabel();
        comboSemester2 = new javax.swing.JComboBox<>();
        btnUpdateGrade1 = new javax.swing.JButton();
        btnViewGrade1 = new javax.swing.JButton();
        comboDegreeLevel = new javax.swing.JComboBox<>();
        lblDescription1 = new javax.swing.JLabel();
        txtProfIDCourse = new javax.swing.JTextField();
        lblCreditHours1 = new javax.swing.JLabel();
        txtCreditHours1 = new javax.swing.JTextField();
        lblCourseName2 = new javax.swing.JLabel();
        txtCourseName2 = new javax.swing.JTextField();
        lblDescription2 = new javax.swing.JLabel();
        txtDescription2 = new javax.swing.JTextField();
        lblCourseID2 = new javax.swing.JLabel();
        txtCourseID2 = new javax.swing.JTextField();
        lblCreditHours2 = new javax.swing.JLabel();
        txtCreditHours2 = new javax.swing.JTextField();
        lblCourseDay2 = new javax.swing.JLabel();
        lblCourseTime2 = new javax.swing.JLabel();
        formattedCourse2Time = new javax.swing.JFormattedTextField();
        formattedCourse1Time = new javax.swing.JFormattedTextField();
        dateChooserCourse1 = new com.toedter.calendar.JDateChooser();
        dateChooserCourse2 = new com.toedter.calendar.JDateChooser();

        leftPane.setBackground(new java.awt.Color(0, 153, 153));

        btnGrades.setText("Manage Grades");
        btnGrades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGradesActionPerformed(evt);
            }
        });

        btnCourses.setText("Course TimeTable");
        btnCourses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCoursesActionPerformed(evt);
            }
        });

        btnLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logout.png"))); // NOI18N
        btnLogOut.setText("Log Out");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout leftPaneLayout = new javax.swing.GroupLayout(leftPane);
        leftPane.setLayout(leftPaneLayout);
        leftPaneLayout.setHorizontalGroup(
            leftPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(leftPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCourses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGrades, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLogOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        leftPaneLayout.setVerticalGroup(
            leftPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPaneLayout.createSequentialGroup()
                .addGap(289, 289, 289)
                .addComponent(btnGrades)
                .addGap(18, 18, 18)
                .addComponent(btnCourses)
                .addGap(233, 233, 233)
                .addComponent(btnLogOut)
                .addContainerGap(339, Short.MAX_VALUE))
        );

        DashboardPanel.setLeftComponent(leftPane);

        rightPane.setLayout(new java.awt.CardLayout());

        workAreaPanel.setBackground(new java.awt.Color(255, 255, 255));
        workAreaPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        workAreaPane.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/blue.jpeg"))); // NOI18N
        workAreaPanel.add(workAreaPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 940));

        rightPane.add(workAreaPanel, "card2");

        studentSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        navigateBackPanel1.setBackground(new java.awt.Color(0, 0, 0));

        btnBackTranscript.setText("Back");

        btnLogoutTranscript.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logout.png"))); // NOI18N
        btnLogoutTranscript.setText("Log Out");

        lblManageGrades.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblManageGrades.setForeground(new java.awt.Color(255, 255, 255));
        lblManageGrades.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblManageGrades.setText("Manage Grades");

        javax.swing.GroupLayout navigateBackPanel1Layout = new javax.swing.GroupLayout(navigateBackPanel1);
        navigateBackPanel1.setLayout(navigateBackPanel1Layout);
        navigateBackPanel1Layout.setHorizontalGroup(
            navigateBackPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navigateBackPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(btnBackTranscript)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 260, Short.MAX_VALUE)
                .addComponent(lblManageGrades, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(202, 202, 202)
                .addComponent(btnLogoutTranscript)
                .addGap(48, 48, 48))
        );
        navigateBackPanel1Layout.setVerticalGroup(
            navigateBackPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navigateBackPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(navigateBackPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBackTranscript)
                    .addComponent(btnLogoutTranscript)
                    .addComponent(lblManageGrades))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        studentSplitPane1.setTopComponent(navigateBackPanel1);

        studentWorkAreaPanel1.setBackground(new java.awt.Color(37, 150, 190));

        tblCourseAssignments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Student Name", "Student ID", "Course ID", "Course Name", "Grade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblCourseAssignments);

        lblCourseID.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblCourseID.setText("Course ID");

        lblCourseName.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblCourseName.setText("Course Name");

        txtGrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGradeActionPerformed(evt);
            }
        });

        lblGrade.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblGrade.setText("Grade");

        txtStudentIDTranscript.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStudentIDTranscriptActionPerformed(evt);
            }
        });

        lblCurrentSemester1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblCurrentSemester1.setText("Current Semester");

        lblStudentIDTranscript.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblStudentIDTranscript.setText("Student ID");

        comboSemester1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Semester", "Fall 2022", "Winter 2022", "Spring 2023", "Summer 2023", "Fall 2023", "Winter 2023", "Spring 2024", "Summer 2024", "Fall 2024", "Winter 2024", " " }));
        comboSemester1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSemester1ActionPerformed(evt);
            }
        });

        btnUpdateGrade.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnUpdateGrade.setText("UPDATE");
        btnUpdateGrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateGradeActionPerformed(evt);
            }
        });

        lblStudentFirstName.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblStudentFirstName.setText("Student Name");

        txtCourseID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCourseIDActionPerformed(evt);
            }
        });

        btnViewGrade.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnViewGrade.setText("VIEW");

        lblCourseDescription.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblCourseDescription.setText("Course Description");

        javax.swing.GroupLayout studentWorkAreaPanel1Layout = new javax.swing.GroupLayout(studentWorkAreaPanel1);
        studentWorkAreaPanel1.setLayout(studentWorkAreaPanel1Layout);
        studentWorkAreaPanel1Layout.setHorizontalGroup(
            studentWorkAreaPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(studentWorkAreaPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblCurrentSemester1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(comboSemester1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(studentWorkAreaPanel1Layout.createSequentialGroup()
                .addContainerGap(213, Short.MAX_VALUE)
                .addGroup(studentWorkAreaPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(studentWorkAreaPanel1Layout.createSequentialGroup()
                        .addComponent(lblStudentIDTranscript, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtStudentIDTranscript, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, studentWorkAreaPanel1Layout.createSequentialGroup()
                        .addComponent(lblCourseID, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtCourseID, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, studentWorkAreaPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(studentWorkAreaPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(studentWorkAreaPanel1Layout.createSequentialGroup()
                                .addComponent(lblGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, studentWorkAreaPanel1Layout.createSequentialGroup()
                                .addComponent(lblCourseDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCourseDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, studentWorkAreaPanel1Layout.createSequentialGroup()
                                .addComponent(lblStudentFirstName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtStudentFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, studentWorkAreaPanel1Layout.createSequentialGroup()
                                .addComponent(lblCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(txtCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(230, 230, 230))
            .addGroup(studentWorkAreaPanel1Layout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addComponent(btnUpdateGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnViewGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        studentWorkAreaPanel1Layout.setVerticalGroup(
            studentWorkAreaPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentWorkAreaPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(studentWorkAreaPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCurrentSemester1)
                    .addComponent(comboSemester1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addGroup(studentWorkAreaPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStudentFirstName)
                    .addComponent(txtStudentFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(studentWorkAreaPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStudentIDTranscript)
                    .addComponent(txtStudentIDTranscript, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(studentWorkAreaPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCourseID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCourseID))
                .addGap(15, 15, 15)
                .addGroup(studentWorkAreaPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCourseName))
                .addGap(18, 18, 18)
                .addGroup(studentWorkAreaPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCourseDescription)
                    .addComponent(txtCourseDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(studentWorkAreaPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGrade)
                    .addComponent(txtGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(studentWorkAreaPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(175, 175, 175))
        );

        studentSplitPane1.setRightComponent(studentWorkAreaPanel1);

        javax.swing.GroupLayout gradesPanelLayout = new javax.swing.GroupLayout(gradesPanel);
        gradesPanel.setLayout(gradesPanelLayout);
        gradesPanelLayout.setHorizontalGroup(
            gradesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gradesPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(studentSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 898, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        gradesPanelLayout.setVerticalGroup(
            gradesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(studentSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        rightPane.add(gradesPanel, "card3");

        studentSplitPane2.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        navigateBackPanel2.setBackground(new java.awt.Color(0, 0, 0));

        btnBackTranscript1.setText("Back");

        btnLogoutTranscript1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logout.png"))); // NOI18N
        btnLogoutTranscript1.setText("Log Out");

        lblCourseManagement.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblCourseManagement.setForeground(new java.awt.Color(255, 255, 255));
        lblCourseManagement.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCourseManagement.setText("Course Timetable");

        javax.swing.GroupLayout navigateBackPanel2Layout = new javax.swing.GroupLayout(navigateBackPanel2);
        navigateBackPanel2.setLayout(navigateBackPanel2Layout);
        navigateBackPanel2Layout.setHorizontalGroup(
            navigateBackPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navigateBackPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(btnBackTranscript1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 260, Short.MAX_VALUE)
                .addComponent(lblCourseManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(202, 202, 202)
                .addComponent(btnLogoutTranscript1)
                .addGap(48, 48, 48))
        );
        navigateBackPanel2Layout.setVerticalGroup(
            navigateBackPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navigateBackPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(navigateBackPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBackTranscript1)
                    .addComponent(btnLogoutTranscript1)
                    .addComponent(lblCourseManagement))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        studentSplitPane2.setTopComponent(navigateBackPanel2);

        studentWorkAreaPanel2.setBackground(new java.awt.Color(37, 150, 190));

        tblTranscripts1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Semester", "Student Name", "Course 1 Name", "Course 1 Day", "Course 1 Time", "Course 2 Name", "Course 2 Day", "Course 2 Time"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblTranscripts1);

        lblCourseName1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblCourseName1.setText("Course 1 Name");

        lblCourseID1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblCourseID1.setText("Course 1 ID");

        lblCourseDay1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblCourseDay1.setText("Course 1 Day");

        txtDescription1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescription1ActionPerformed(evt);
            }
        });

        lblProfIDCourse.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblProfIDCourse.setText("Professor ID");

        lblCourseTime1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblCourseTime1.setText("Course 1 Time");

        txtMajorCourse.setEditable(false);
        txtMajorCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMajorCourseActionPerformed(evt);
            }
        });

        lblMajorCourse.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblMajorCourse.setText("Major");

        lblDegreeLevelCourse.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblDegreeLevelCourse.setText("Degree Level");

        lblCurrentSemesterCourse.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblCurrentSemesterCourse.setText("Current Semester");

        comboSemester2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Semester", "Fall 2022", "Winter 2022", "Spring 2023", "Summer 2023", "Fall 2023", "Winter 2023", "Spring 2024", "Summer 2024", "Fall 2024", "Winter 2024", " " }));

        btnUpdateGrade1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnUpdateGrade1.setText("UPDATE");

        btnViewGrade1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnViewGrade1.setText("VIEW");

        comboDegreeLevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Level", "Undergraduate ", "Graduate" }));

        lblDescription1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblDescription1.setText("Description 1");

        txtProfIDCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProfIDCourseActionPerformed(evt);
            }
        });

        lblCreditHours1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblCreditHours1.setText("Credit Hours");

        txtCreditHours1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCreditHours1ActionPerformed(evt);
            }
        });

        lblCourseName2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblCourseName2.setText("Course 2 Name");

        lblDescription2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblDescription2.setText("Description 2");

        txtDescription2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescription2ActionPerformed(evt);
            }
        });

        lblCourseID2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblCourseID2.setText("Course 2 ID");

        lblCreditHours2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblCreditHours2.setText("Credit Hours");

        txtCreditHours2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCreditHours2ActionPerformed(evt);
            }
        });

        lblCourseDay2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblCourseDay2.setText("Course 2 Day");

        lblCourseTime2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblCourseTime2.setText("Course 2 Time");

        formattedCourse2Time.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));

        formattedCourse1Time.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));

        javax.swing.GroupLayout studentWorkAreaPanel2Layout = new javax.swing.GroupLayout(studentWorkAreaPanel2);
        studentWorkAreaPanel2.setLayout(studentWorkAreaPanel2Layout);
        studentWorkAreaPanel2Layout.setHorizontalGroup(
            studentWorkAreaPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
            .addGroup(studentWorkAreaPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(studentWorkAreaPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(studentWorkAreaPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblCourseID1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblCourseDay1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblCourseName1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblMajorCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblCourseName2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblCourseID2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblCourseDay2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblCurrentSemesterCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(studentWorkAreaPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(studentWorkAreaPanel2Layout.createSequentialGroup()
                        .addGroup(studentWorkAreaPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCourseID1, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                            .addComponent(txtCourseName1)
                            .addComponent(txtCourseName2)
                            .addComponent(txtCourseID2, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                            .addComponent(txtMajorCourse, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                            .addComponent(dateChooserCourse1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dateChooserCourse2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(studentWorkAreaPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(studentWorkAreaPanel2Layout.createSequentialGroup()
                                .addGroup(studentWorkAreaPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblProfIDCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCourseTime1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDescription1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(studentWorkAreaPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(studentWorkAreaPanel2Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(txtDescription1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtProfIDCourse)
                                    .addComponent(formattedCourse1Time)))
                            .addGroup(studentWorkAreaPanel2Layout.createSequentialGroup()
                                .addComponent(lblDescription2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDescription2))
                            .addGroup(studentWorkAreaPanel2Layout.createSequentialGroup()
                                .addComponent(lblCreditHours1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCreditHours2))
                            .addGroup(studentWorkAreaPanel2Layout.createSequentialGroup()
                                .addComponent(lblCreditHours2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCreditHours1))
                            .addGroup(studentWorkAreaPanel2Layout.createSequentialGroup()
                                .addComponent(lblCourseTime2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(formattedCourse2Time))))
                    .addGroup(studentWorkAreaPanel2Layout.createSequentialGroup()
                        .addComponent(comboSemester2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblDegreeLevelCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboDegreeLevel, 0, 240, Short.MAX_VALUE)))
                .addGap(62, 62, 62))
            .addGroup(studentWorkAreaPanel2Layout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addComponent(btnViewGrade1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnUpdateGrade1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        studentWorkAreaPanel2Layout.setVerticalGroup(
            studentWorkAreaPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentWorkAreaPanel2Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(studentWorkAreaPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCurrentSemesterCourse)
                    .addComponent(comboSemester2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDegreeLevelCourse)
                    .addComponent(comboDegreeLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(studentWorkAreaPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMajorCourse)
                    .addComponent(txtMajorCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblProfIDCourse)
                    .addComponent(txtProfIDCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(studentWorkAreaPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCourseName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCourseName1)
                    .addComponent(txtDescription1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDescription1))
                .addGap(18, 18, 18)
                .addGroup(studentWorkAreaPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(studentWorkAreaPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCourseID1)
                        .addComponent(txtCourseID1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblCreditHours1))
                    .addComponent(txtCreditHours2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(studentWorkAreaPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(studentWorkAreaPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCourseDay1)
                        .addComponent(lblCourseTime1)
                        .addComponent(formattedCourse1Time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(dateChooserCourse1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(studentWorkAreaPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCourseName2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCourseName2)
                    .addComponent(lblDescription2)
                    .addComponent(txtDescription2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(studentWorkAreaPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCourseID2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCourseID2)
                    .addComponent(txtCreditHours1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCreditHours2))
                .addGap(19, 19, 19)
                .addGroup(studentWorkAreaPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(studentWorkAreaPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCourseTime2)
                        .addComponent(lblCourseDay2)
                        .addComponent(formattedCourse2Time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(dateChooserCourse2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(studentWorkAreaPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewGrade1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateGrade1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(112, 112, 112))
        );

        studentSplitPane2.setRightComponent(studentWorkAreaPanel2);

        javax.swing.GroupLayout coursesPanelLayout = new javax.swing.GroupLayout(coursesPanel);
        coursesPanel.setLayout(coursesPanelLayout);
        coursesPanelLayout.setHorizontalGroup(
            coursesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, coursesPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(studentSplitPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 898, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        coursesPanelLayout.setVerticalGroup(
            coursesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(studentSplitPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        rightPane.add(coursesPanel, "card3");

        DashboardPanel.setRightComponent(rightPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DashboardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1049, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DashboardPanel))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGradesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGradesActionPerformed
        // TODO add your handling code here:
        workAreaPanel.setVisible(false);
        gradesPanel.setVisible(true);
        coursesPanel.setVisible(false);

    }//GEN-LAST:event_btnGradesActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
        switchToMainFrame();
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void txtGradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGradeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGradeActionPerformed

    private void txtStudentIDTranscriptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStudentIDTranscriptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStudentIDTranscriptActionPerformed

    private void txtCourseIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCourseIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCourseIDActionPerformed

    private void txtDescription1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescription1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescription1ActionPerformed

    private void txtMajorCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMajorCourseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMajorCourseActionPerformed

    private void txtProfIDCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProfIDCourseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProfIDCourseActionPerformed

    private void txtCreditHours1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCreditHours1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCreditHours1ActionPerformed

    private void txtDescription2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescription2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescription2ActionPerformed

    private void txtCreditHours2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCreditHours2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCreditHours2ActionPerformed

    private void btnUpdateGradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateGradeActionPerformed
        // TODO add your handling code here:
     
         
         
    }//GEN-LAST:event_btnUpdateGradeActionPerformed

    private void btnCoursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCoursesActionPerformed
        // TODO add your handling code here:
        workAreaPanel.setVisible(false);
        gradesPanel.setVisible(false);
        coursesPanel.setVisible(true);
        
    }//GEN-LAST:event_btnCoursesActionPerformed

    private void comboSemester1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSemester1ActionPerformed
        // TODO add your handling code here:
//        Course course = null;
        if(comboSemester1.getSelectedItem()!=null){
                String currentSemester = comboSemester1.getSelectedItem().toString();
                if(!currentSemester.equalsIgnoreCase("Select Semester")){
                    List<Course> courseBySem = ecoSystem.getCourseDirectoryRef().getCourseDirectory()
                            .stream().filter(c-> c.getSemester().equalsIgnoreCase(currentSemester)
                                    &&(c.getProfessorName().equalsIgnoreCase(person.getPersonName()))).toList();
                    Course course = courseBySem.get(0);
                    List<CourseAssignment> courseAssignments = ecoSystem.getCourseAssignmentRef().getCourseAssignmentDirectory()
                        .stream().filter(ca -> ca.getCourseID() == course.getCourseID()).toList();
                populateCourseAssignmentsTable(courseAssignments);
                    
                }
                
                
            }
        
        
    }//GEN-LAST:event_comboSemester1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane DashboardPanel;
    private javax.swing.JButton btnBackTranscript;
    private javax.swing.JButton btnBackTranscript1;
    private javax.swing.JButton btnCourses;
    private javax.swing.JButton btnGrades;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnLogoutTranscript;
    private javax.swing.JButton btnLogoutTranscript1;
    private javax.swing.JButton btnUpdateGrade;
    private javax.swing.JButton btnUpdateGrade1;
    private javax.swing.JButton btnViewGrade;
    private javax.swing.JButton btnViewGrade1;
    private javax.swing.JComboBox<String> comboDegreeLevel;
    private javax.swing.JComboBox<String> comboSemester1;
    private javax.swing.JComboBox<String> comboSemester2;
    private javax.swing.JPanel coursesPanel;
    private com.toedter.calendar.JDateChooser dateChooserCourse1;
    private com.toedter.calendar.JDateChooser dateChooserCourse2;
    private javax.swing.JFormattedTextField formattedCourse1Time;
    private javax.swing.JFormattedTextField formattedCourse2Time;
    private javax.swing.JPanel gradesPanel;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblCourseDay1;
    private javax.swing.JLabel lblCourseDay2;
    private javax.swing.JLabel lblCourseDescription;
    private javax.swing.JLabel lblCourseID;
    private javax.swing.JLabel lblCourseID1;
    private javax.swing.JLabel lblCourseID2;
    private javax.swing.JLabel lblCourseManagement;
    private javax.swing.JLabel lblCourseName;
    private javax.swing.JLabel lblCourseName1;
    private javax.swing.JLabel lblCourseName2;
    private javax.swing.JLabel lblCourseTime1;
    private javax.swing.JLabel lblCourseTime2;
    private javax.swing.JLabel lblCreditHours1;
    private javax.swing.JLabel lblCreditHours2;
    private javax.swing.JLabel lblCurrentSemester1;
    private javax.swing.JLabel lblCurrentSemesterCourse;
    private javax.swing.JLabel lblDegreeLevelCourse;
    private javax.swing.JLabel lblDescription1;
    private javax.swing.JLabel lblDescription2;
    private javax.swing.JLabel lblGrade;
    private javax.swing.JLabel lblMajorCourse;
    private javax.swing.JLabel lblManageGrades;
    private javax.swing.JLabel lblProfIDCourse;
    private javax.swing.JLabel lblStudentFirstName;
    private javax.swing.JLabel lblStudentIDTranscript;
    private javax.swing.JPanel leftPane;
    private javax.swing.JPanel navigateBackPanel1;
    private javax.swing.JPanel navigateBackPanel2;
    private javax.swing.JLayeredPane rightPane;
    private javax.swing.JSplitPane studentSplitPane1;
    private javax.swing.JSplitPane studentSplitPane2;
    private javax.swing.JPanel studentWorkAreaPanel1;
    private javax.swing.JPanel studentWorkAreaPanel2;
    private javax.swing.JTable tblCourseAssignments;
    private javax.swing.JTable tblTranscripts1;
    private javax.swing.JTextField txtCourseDescription;
    private javax.swing.JTextField txtCourseID;
    private javax.swing.JTextField txtCourseID1;
    private javax.swing.JTextField txtCourseID2;
    private javax.swing.JTextField txtCourseName;
    private javax.swing.JTextField txtCourseName1;
    private javax.swing.JTextField txtCourseName2;
    private javax.swing.JTextField txtCreditHours1;
    private javax.swing.JTextField txtCreditHours2;
    private javax.swing.JTextField txtDescription1;
    private javax.swing.JTextField txtDescription2;
    private javax.swing.JTextField txtGrade;
    private javax.swing.JTextField txtMajorCourse;
    private javax.swing.JTextField txtProfIDCourse;
    private javax.swing.JTextField txtStudentFirstName;
    private javax.swing.JTextField txtStudentIDTranscript;
    private javax.swing.JLabel workAreaPane;
    private javax.swing.JPanel workAreaPanel;
    // End of variables declaration//GEN-END:variables

       private void switchToMainFrame() {
        this.setVisible(false);
        MainJFrame mainFrame = (MainJFrame) SwingUtilities.getRoot(this);
        mainFrame.removeProfessorDashboard();
        mainFrame.setVisible(true);
    }


    private void populateCourseAssignmentsTable(List<CourseAssignment> courseAssignments) {
          DefaultTableModel model = (DefaultTableModel) tblCourseAssignments.getModel();
        model.setRowCount(0);
        for(CourseAssignment courseAssignment : courseAssignments){
            Object[] rowData = new Object[5];
            rowData[0] = ecoSystem.getStudentDirectoryRef().getStudentDirectory()
                    .stream().filter(s -> s.getStudentID()==courseAssignment.getStudentID())
                    .findFirst().orElse(null).getPersonName();
            rowData[1] = courseAssignment.getStudentID();
            rowData[2] = courseAssignment.getCourseID();
            rowData[3] = ecoSystem.getCourseDirectoryRef().getCourseDirectory()
                    .stream().filter(s -> s.getCourseID()==courseAssignment.getCourseID())
                    .findFirst().orElse(null).getCourseName();
            rowData[4] = ecoSystem.getCourseDirectoryRef().getCourseDirectory()
                    .stream().filter(s -> s.getCourseID()==courseAssignment.getCourseID())
                    .findFirst().orElse(null).getCourseDescription();
            rowData[5] = ecoSystem.getProfessorDirectoryRef().getProfessorDirectory()
                    .stream().filter(p -> p.getProfessorID()==courseAssignment.getProfessorID())
                    .findFirst().orElse(null).getPersonName();
        }
        
    }
}
