/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.UniversityManagement;

import businesslogic.City;
import businesslogic.Community;
import businesslogic.UniversityManagement.Degree;
import businesslogic.UniversityManagement.Student;
import businesslogic.UniversityManagement.UniversityAdmin;
import ui.school.SchoolAdminRole.*;
import java.awt.CardLayout;
import java.awt.Image;
import java.util.List;
import java.io.File;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JSplitPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author drashtibhingradiya
 */
public class UniversityAdminDashboard extends javax.swing.JPanel {
    
//    public static JPanel universityAdminDashboard;
    /**
     * Creates new form DashboardJPanel
     */
   private ImageIcon studentPhoto;
   private String photoPath = "/icons/default.jpg";
   
    
    public UniversityAdminDashboard() {
        initComponents();
        populateTable();
        setSize(1060, 770);
        workAreaPanel.setVisible(true);
        studentPanel.setVisible(false);   
        genderButtonGroup.add(btnMale);
        genderButtonGroup.add(btnFemale);
        genderButtonGroup.add(btnNonBinary);
    }
    
    
        private void setPhoto(String imagePath) {
        ImageIcon photo = new ImageIcon(imagePath);
        Image photoResized = photo.getImage().getScaledInstance(134,138,4); //lblpicpreview.getSize().width, lblpicpreview.getSize().height,4);
        lblStudentPhoto.setIcon(new ImageIcon(photoResized));
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderButtonGroup = new javax.swing.ButtonGroup();
        DashboardPanel = new javax.swing.JSplitPane();
        leftPane = new javax.swing.JPanel();
        btnFaculty = new javax.swing.JButton();
        btnStudents = new javax.swing.JButton();
        btnMealOrders = new javax.swing.JButton();
        btnReports = new javax.swing.JButton();
        btnDormitories = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        btnCourses = new javax.swing.JButton();
        rightPane = new javax.swing.JLayeredPane();
        workAreaPanel = new javax.swing.JPanel();
        workAreaPane = new javax.swing.JLabel();
        studentPanel = new javax.swing.JPanel();
        studentSplitPane = new javax.swing.JSplitPane();
        navigateBackPanel = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        lblManageStudents = new javax.swing.JLabel();
        studentWorkAreaPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStudents = new javax.swing.JTable();
        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        txtEmailAddress = new javax.swing.JTextField();
        txtSSN = new javax.swing.JTextField();
        lblFirstName = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        lblEmailAddress = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        btnMale = new javax.swing.JRadioButton();
        btnFemale = new javax.swing.JRadioButton();
        btnNonBinary = new javax.swing.JRadioButton();
        lblSSN = new javax.swing.JLabel();
        txtPhoneNumber = new javax.swing.JTextField();
        dateChooser = new com.toedter.calendar.JDateChooser();
        lblDateofBirth = new javax.swing.JLabel();
        lblDateofBirth1 = new javax.swing.JLabel();
        txtStudentID = new javax.swing.JTextField();
        passwordFieldStudent = new javax.swing.JPasswordField();
        lblPassword = new javax.swing.JLabel();
        lblStudentID = new javax.swing.JLabel();
        txtInstituteCode = new javax.swing.JTextField();
        lblStudentID1 = new javax.swing.JLabel();
        lblStudentDegreeLevel = new javax.swing.JLabel();
        lblCurrentSemester = new javax.swing.JLabel();
        lblGraduationYear = new javax.swing.JLabel();
        lblPhoto = new javax.swing.JLabel();
        comboSemester = new javax.swing.JComboBox<>();
        btnCreate = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        lblStudentPhoto = new javax.swing.JLabel();
        btnPhoto = new javax.swing.JButton();
        txtGradYear = new javax.swing.JTextField();
        lblStudentMajor = new javax.swing.JLabel();
        txtStudentMajor = new javax.swing.JTextField();
        comboDegreeLevel = new javax.swing.JComboBox<>();
        facultyPanel = new javax.swing.JPanel();
        facultySplitPane = new javax.swing.JSplitPane();
        navigateBackPanelFaculty = new javax.swing.JPanel();
        btnBackFaculty = new javax.swing.JButton();
        btnLogoutFaculty = new javax.swing.JButton();
        lblManageFaculty = new javax.swing.JLabel();
        professorWorkAreaPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblStudents1 = new javax.swing.JTable();
        txtFirstNameProf = new javax.swing.JTextField();
        txtLastNameProf = new javax.swing.JTextField();
        txtEmailAddressProf = new javax.swing.JTextField();
        txtSSNProf = new javax.swing.JTextField();
        lblFirstNameProf = new javax.swing.JLabel();
        lblLastNameProf = new javax.swing.JLabel();
        lblEmailAddressProf = new javax.swing.JLabel();
        lblGender1 = new javax.swing.JLabel();
        btnMale1 = new javax.swing.JRadioButton();
        btnFemale1 = new javax.swing.JRadioButton();
        btnNonBinary1 = new javax.swing.JRadioButton();
        lblSSNProf = new javax.swing.JLabel();
        txtPhoneNumberProf = new javax.swing.JTextField();
        dateOfBirthProf = new com.toedter.calendar.JDateChooser();
        lblDobProf = new javax.swing.JLabel();
        lblPhoneNumberProf = new javax.swing.JLabel();
        txtProfessorID = new javax.swing.JTextField();
        PasswordProfessor = new javax.swing.JPasswordField();
        lblPasswordProfessor = new javax.swing.JLabel();
        lblProfessorID = new javax.swing.JLabel();
        txtInstituteCodeProf = new javax.swing.JTextField();
        lblInstituteCodeProf = new javax.swing.JLabel();
        txtProfessorPhoto = new javax.swing.JTextField();
        lblPhotoProfessor = new javax.swing.JLabel();
        btnCreateProf = new javax.swing.JButton();
        btnViewProf = new javax.swing.JButton();
        btnUpdateProf = new javax.swing.JButton();
        btnDeleteProf = new javax.swing.JButton();
        startDateChooser = new com.toedter.calendar.JDateChooser();
        lblProfessorStartDate = new javax.swing.JLabel();
        coursesPanel = new javax.swing.JPanel();
        studentSplitPane1 = new javax.swing.JSplitPane();
        navigateBackPanel1 = new javax.swing.JPanel();
        btnBackTranscript = new javax.swing.JButton();
        btnLogoutTranscript = new javax.swing.JButton();
        lblManageCourses = new javax.swing.JLabel();
        studentWorkAreaPanel1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblTranscripts = new javax.swing.JTable();
        txtCourseID = new javax.swing.JTextField();
        txtCourseDescription = new javax.swing.JTextField();
        txtCourseName = new javax.swing.JTextField();
        lblCourseID = new javax.swing.JLabel();
        lblCourseName = new javax.swing.JLabel();
        lblCourseDescription = new javax.swing.JLabel();
        txtGrade1 = new javax.swing.JTextField();
        lblProfessorIDCourse = new javax.swing.JLabel();
        lblStudentID5 = new javax.swing.JLabel();
        txtProfessorName = new javax.swing.JTextField();
        lblCurrentSemester1 = new javax.swing.JLabel();
        lblProfessorName = new javax.swing.JLabel();
        comboSemester1 = new javax.swing.JComboBox<>();
        btnUpdateCourse = new javax.swing.JButton();
        txtProfessorIDCourse = new javax.swing.JTextField();
        btnViewCourse = new javax.swing.JButton();
        btnCreateCourse = new javax.swing.JButton();
        btnDeleteCourse = new javax.swing.JButton();

        leftPane.setBackground(new java.awt.Color(0, 153, 153));

        btnFaculty.setText("Manage Faculty");

        btnStudents.setText("Manage Students");
        btnStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentsActionPerformed(evt);
            }
        });

        btnMealOrders.setText("Meal Orders");

        btnReports.setText("View Reports");

        btnDormitories.setText("Manage Dormitories");

        btnLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logout.png"))); // NOI18N
        btnLogOut.setText("Log Out");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        btnCourses.setText("Manage Courses");

        javax.swing.GroupLayout leftPaneLayout = new javax.swing.GroupLayout(leftPane);
        leftPane.setLayout(leftPaneLayout);
        leftPaneLayout.setHorizontalGroup(
            leftPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(leftPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDormitories, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnReports, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMealOrders, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnStudents, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFaculty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLogOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCourses, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        leftPaneLayout.setVerticalGroup(
            leftPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPaneLayout.createSequentialGroup()
                .addGap(213, 213, 213)
                .addComponent(btnStudents)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnFaculty)
                .addGap(18, 18, 18)
                .addComponent(btnCourses)
                .addGap(18, 18, 18)
                .addComponent(btnMealOrders)
                .addGap(18, 18, 18)
                .addComponent(btnReports)
                .addGap(18, 18, 18)
                .addComponent(btnDormitories)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 287, Short.MAX_VALUE)
                .addComponent(btnLogOut)
                .addGap(126, 126, 126))
        );

        DashboardPanel.setLeftComponent(leftPane);

        rightPane.setLayout(new java.awt.CardLayout());

        workAreaPanel.setBackground(new java.awt.Color(255, 255, 255));
        workAreaPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        workAreaPane.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/blue.jpeg"))); // NOI18N
        workAreaPanel.add(workAreaPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 840));

        rightPane.add(workAreaPanel, "card2");

        studentSplitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        navigateBackPanel.setBackground(new java.awt.Color(0, 0, 0));

        btnBack.setText("Back");

        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logout.png"))); // NOI18N
        btnLogout.setText("Log Out");

        lblManageStudents.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblManageStudents.setForeground(new java.awt.Color(255, 255, 255));
        lblManageStudents.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblManageStudents.setText("Manage Student");

        javax.swing.GroupLayout navigateBackPanelLayout = new javax.swing.GroupLayout(navigateBackPanel);
        navigateBackPanel.setLayout(navigateBackPanelLayout);
        navigateBackPanelLayout.setHorizontalGroup(
            navigateBackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navigateBackPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 279, Short.MAX_VALUE)
                .addComponent(lblManageStudents)
                .addGap(236, 236, 236)
                .addComponent(btnLogout)
                .addGap(48, 48, 48))
        );
        navigateBackPanelLayout.setVerticalGroup(
            navigateBackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navigateBackPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(navigateBackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnLogout)
                    .addComponent(lblManageStudents))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        studentSplitPane.setTopComponent(navigateBackPanel);

        studentWorkAreaPanel.setBackground(new java.awt.Color(37, 150, 190));

        tblStudents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Student Name", "Student ID", "Email Address", "Gender", "Phone Number", "Institute Code", "Degree Level", "Major", "Current Semester", "Graduation Year"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblStudents);

        lblFirstName.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblFirstName.setText("First Name");

        lblLastName.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblLastName.setText("Last Name");

        lblEmailAddress.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblEmailAddress.setText("Email Address");

        lblGender.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblGender.setText("Gender");

        btnMale.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnMale.setText("Male");

        btnFemale.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnFemale.setText("Female");

        btnNonBinary.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnNonBinary.setText("Non Binary");

        lblSSN.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblSSN.setText("SSN");

        txtPhoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneNumberActionPerformed(evt);
            }
        });

        lblDateofBirth.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblDateofBirth.setText("Date of Birth");

        lblDateofBirth1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblDateofBirth1.setText("Phone Number");

        txtStudentID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStudentIDActionPerformed(evt);
            }
        });

        passwordFieldStudent.setText("jPasswordField1");

        lblPassword.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblPassword.setText("Password");

        lblStudentID.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblStudentID.setText("Student ID");

        txtInstituteCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInstituteCodeActionPerformed(evt);
            }
        });

        lblStudentID1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblStudentID1.setText("Institute Code");

        lblStudentDegreeLevel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblStudentDegreeLevel.setText("Degree Level");

        lblCurrentSemester.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblCurrentSemester.setText("Current Semester");

        lblGraduationYear.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblGraduationYear.setText("Graduation Year");

        lblPhoto.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblPhoto.setText("Student Photo");

        comboSemester.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Semester", "Fall 2022", "Winter 2022", "Spring 2023", "Summer 2023", "Fall 2023", "Winter 2023", "Spring 2024", "Summer 2024", "Fall 2024", "Winter 2024", " " }));

        btnCreate.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnCreate.setText("SAVE");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnView.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnView.setText("VIEW");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnUpdate.setText("UPDATE");

        btnDelete.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnDelete.setText("DELETE");

        lblStudentPhoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        btnPhoto.setText("Attach Photo");
        btnPhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPhotoActionPerformed(evt);
            }
        });

        lblStudentMajor.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblStudentMajor.setText("Student Major");

        txtStudentMajor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStudentMajorActionPerformed(evt);
            }
        });

        comboDegreeLevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Level", "Undergraduate", "Graduate" }));

        javax.swing.GroupLayout studentWorkAreaPanelLayout = new javax.swing.GroupLayout(studentWorkAreaPanel);
        studentWorkAreaPanel.setLayout(studentWorkAreaPanelLayout);
        studentWorkAreaPanelLayout.setHorizontalGroup(
            studentWorkAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, studentWorkAreaPanelLayout.createSequentialGroup()
                .addGroup(studentWorkAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(studentWorkAreaPanelLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(studentWorkAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblGraduationYear, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGender, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDateofBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(studentWorkAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSSN, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                            .addComponent(txtEmailAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                            .addComponent(txtLastName, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                            .addComponent(txtFirstName)
                            .addGroup(studentWorkAreaPanelLayout.createSequentialGroup()
                                .addComponent(btnMale)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnFemale)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnNonBinary))
                            .addComponent(dateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtGradYear, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE))
                        .addGroup(studentWorkAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(studentWorkAreaPanelLayout.createSequentialGroup()
                                .addGroup(studentWorkAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(studentWorkAreaPanelLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(studentWorkAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblPassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblDateofBirth1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(28, 28, 28))
                                    .addGroup(studentWorkAreaPanelLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(studentWorkAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblStudentID1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblStudentID, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblStudentDegreeLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblCurrentSemester, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblStudentMajor, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(studentWorkAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtPhoneNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                                    .addComponent(txtStudentID, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                                    .addComponent(passwordFieldStudent)
                                    .addComponent(txtInstituteCode, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                                    .addComponent(txtStudentMajor, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                                    .addComponent(comboDegreeLevel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(studentWorkAreaPanelLayout.createSequentialGroup()
                                .addGap(177, 177, 177)
                                .addComponent(comboSemester, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(studentWorkAreaPanelLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(studentWorkAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(studentWorkAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(studentWorkAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblPhoto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblStudentPhoto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))))
                .addGap(61, 61, 61))
            .addComponent(jScrollPane1)
        );
        studentWorkAreaPanelLayout.setVerticalGroup(
            studentWorkAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentWorkAreaPanelLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(studentWorkAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFirstName)
                    .addComponent(lblDateofBirth1)
                    .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(studentWorkAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLastName)
                    .addComponent(passwordFieldStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPassword))
                .addGap(18, 18, 18)
                .addGroup(studentWorkAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmailAddress)
                    .addComponent(txtStudentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStudentID))
                .addGap(18, 18, 18)
                .addGroup(studentWorkAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGender)
                    .addComponent(btnMale)
                    .addComponent(btnFemale)
                    .addComponent(btnNonBinary)
                    .addComponent(txtInstituteCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStudentID1))
                .addGap(21, 21, 21)
                .addGroup(studentWorkAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSSN)
                    .addComponent(lblStudentDegreeLevel)
                    .addComponent(comboDegreeLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(studentWorkAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDateofBirth)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, studentWorkAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblStudentMajor)
                        .addComponent(txtStudentMajor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17)
                .addGroup(studentWorkAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGraduationYear)
                    .addComponent(txtGradYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCurrentSemester)
                    .addComponent(comboSemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(lblPhoto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(studentWorkAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(studentWorkAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(studentWorkAreaPanelLayout.createSequentialGroup()
                            .addGroup(studentWorkAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(studentWorkAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(36, 36, 36))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, studentWorkAreaPanelLayout.createSequentialGroup()
                            .addComponent(lblStudentPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap()))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, studentWorkAreaPanelLayout.createSequentialGroup()
                        .addComponent(btnPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52))))
        );

        studentSplitPane.setRightComponent(studentWorkAreaPanel);

        javax.swing.GroupLayout studentPanelLayout = new javax.swing.GroupLayout(studentPanel);
        studentPanel.setLayout(studentPanelLayout);
        studentPanelLayout.setHorizontalGroup(
            studentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, studentPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(studentSplitPane, javax.swing.GroupLayout.PREFERRED_SIZE, 898, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        studentPanelLayout.setVerticalGroup(
            studentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(studentSplitPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        rightPane.add(studentPanel, "card3");

        facultySplitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        navigateBackPanelFaculty.setBackground(new java.awt.Color(0, 0, 0));

        btnBackFaculty.setText("Back");

        btnLogoutFaculty.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logout.png"))); // NOI18N
        btnLogoutFaculty.setText("Log Out");

        lblManageFaculty.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblManageFaculty.setForeground(new java.awt.Color(255, 255, 255));
        lblManageFaculty.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblManageFaculty.setText("Manage Faculty");

        javax.swing.GroupLayout navigateBackPanelFacultyLayout = new javax.swing.GroupLayout(navigateBackPanelFaculty);
        navigateBackPanelFaculty.setLayout(navigateBackPanelFacultyLayout);
        navigateBackPanelFacultyLayout.setHorizontalGroup(
            navigateBackPanelFacultyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navigateBackPanelFacultyLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(btnBackFaculty)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 283, Short.MAX_VALUE)
                .addComponent(lblManageFaculty)
                .addGap(236, 236, 236)
                .addComponent(btnLogoutFaculty)
                .addGap(48, 48, 48))
        );
        navigateBackPanelFacultyLayout.setVerticalGroup(
            navigateBackPanelFacultyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navigateBackPanelFacultyLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(navigateBackPanelFacultyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBackFaculty)
                    .addComponent(btnLogoutFaculty)
                    .addComponent(lblManageFaculty))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        facultySplitPane.setTopComponent(navigateBackPanelFaculty);

        professorWorkAreaPanel.setBackground(new java.awt.Color(37, 150, 190));

        tblStudents1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "First Name", "Email Address", "Gender", "Phone Number", "Professor ID", "Institute Code", "Start Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblStudents1);

        lblFirstNameProf.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblFirstNameProf.setText("First Name");

        lblLastNameProf.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblLastNameProf.setText("Last Name");

        lblEmailAddressProf.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblEmailAddressProf.setText("Email Address");

        lblGender1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblGender1.setText("Gender");

        btnMale1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnMale1.setText("Male");

        btnFemale1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnFemale1.setText("Female");

        btnNonBinary1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnNonBinary1.setText("Non Binary");

        lblSSNProf.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblSSNProf.setText("SSN");

        txtPhoneNumberProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneNumberProfActionPerformed(evt);
            }
        });

        lblDobProf.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblDobProf.setText("Date of Birth");

        lblPhoneNumberProf.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblPhoneNumberProf.setText("Phone Number");

        txtProfessorID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProfessorIDActionPerformed(evt);
            }
        });

        PasswordProfessor.setText("jPasswordField1");

        lblPasswordProfessor.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblPasswordProfessor.setText("Password");

        lblProfessorID.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblProfessorID.setText("Professor ID");

        txtInstituteCodeProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInstituteCodeProfActionPerformed(evt);
            }
        });

        lblInstituteCodeProf.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblInstituteCodeProf.setText("Institute Code");

        txtProfessorPhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProfessorPhotoActionPerformed(evt);
            }
        });

        lblPhotoProfessor.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblPhotoProfessor.setText("Professor Photo");

        btnCreateProf.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnCreateProf.setText("CREATE");

        btnViewProf.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnViewProf.setText("VIEW");

        btnUpdateProf.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnUpdateProf.setText("UPDATE");

        btnDeleteProf.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnDeleteProf.setText("DELETE");

        lblProfessorStartDate.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblProfessorStartDate.setText("Start Date");

        javax.swing.GroupLayout professorWorkAreaPanelLayout = new javax.swing.GroupLayout(professorWorkAreaPanel);
        professorWorkAreaPanel.setLayout(professorWorkAreaPanelLayout);
        professorWorkAreaPanelLayout.setHorizontalGroup(
            professorWorkAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(professorWorkAreaPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 877, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 21, Short.MAX_VALUE))
            .addGroup(professorWorkAreaPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(professorWorkAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblFirstNameProf, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLastNameProf, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmailAddressProf, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGender1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSSNProf, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDobProf, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(professorWorkAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtSSNProf, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                    .addComponent(txtEmailAddressProf, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                    .addComponent(txtLastNameProf, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                    .addComponent(txtFirstNameProf)
                    .addGroup(professorWorkAreaPanelLayout.createSequentialGroup()
                        .addComponent(btnMale1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFemale1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnNonBinary1))
                    .addComponent(dateOfBirthProf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(professorWorkAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(professorWorkAreaPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(professorWorkAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPasswordProfessor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPhoneNumberProf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28))
                    .addGroup(professorWorkAreaPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(professorWorkAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblProfessorID, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblInstituteCodeProf, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPhotoProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblProfessorStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(professorWorkAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPhoneNumberProf, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                    .addComponent(txtProfessorID, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                    .addComponent(PasswordProfessor)
                    .addComponent(txtInstituteCodeProf, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                    .addComponent(txtProfessorPhoto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                    .addComponent(startDateChooser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(62, 62, 62))
            .addGroup(professorWorkAreaPanelLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(professorWorkAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCreateProf, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateProf, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(professorWorkAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnViewProf, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteProf, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        professorWorkAreaPanelLayout.setVerticalGroup(
            professorWorkAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(professorWorkAreaPanelLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(professorWorkAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFirstNameProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFirstNameProf)
                    .addComponent(lblPhoneNumberProf)
                    .addComponent(txtPhoneNumberProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(professorWorkAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLastNameProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLastNameProf)
                    .addComponent(PasswordProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPasswordProfessor))
                .addGap(18, 18, 18)
                .addGroup(professorWorkAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmailAddressProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmailAddressProf)
                    .addComponent(txtProfessorID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblProfessorID))
                .addGap(18, 18, 18)
                .addGroup(professorWorkAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(professorWorkAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblGender1)
                        .addComponent(btnMale1)
                        .addComponent(btnFemale1)
                        .addComponent(btnNonBinary1)
                        .addComponent(lblProfessorStartDate))
                    .addComponent(startDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(professorWorkAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSSNProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSSNProf)
                    .addComponent(txtInstituteCodeProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblInstituteCodeProf))
                .addGap(18, 18, 18)
                .addGroup(professorWorkAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateOfBirthProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDobProf)
                    .addGroup(professorWorkAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtProfessorPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblPhotoProfessor)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addGroup(professorWorkAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewProf, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCreateProf, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(professorWorkAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteProf, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateProf, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );

        facultySplitPane.setRightComponent(professorWorkAreaPanel);

        javax.swing.GroupLayout facultyPanelLayout = new javax.swing.GroupLayout(facultyPanel);
        facultyPanel.setLayout(facultyPanelLayout);
        facultyPanelLayout.setHorizontalGroup(
            facultyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, facultyPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(facultySplitPane, javax.swing.GroupLayout.PREFERRED_SIZE, 898, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        facultyPanelLayout.setVerticalGroup(
            facultyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(facultySplitPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        rightPane.add(facultyPanel, "card3");

        studentSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        navigateBackPanel1.setBackground(new java.awt.Color(0, 0, 0));

        btnBackTranscript.setText("Back");

        btnLogoutTranscript.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logout.png"))); // NOI18N
        btnLogoutTranscript.setText("Log Out");

        lblManageCourses.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblManageCourses.setForeground(new java.awt.Color(255, 255, 255));
        lblManageCourses.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblManageCourses.setText("Manage Courses");

        javax.swing.GroupLayout navigateBackPanel1Layout = new javax.swing.GroupLayout(navigateBackPanel1);
        navigateBackPanel1.setLayout(navigateBackPanel1Layout);
        navigateBackPanel1Layout.setHorizontalGroup(
            navigateBackPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navigateBackPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(btnBackTranscript)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 274, Short.MAX_VALUE)
                .addComponent(lblManageCourses)
                .addGap(236, 236, 236)
                .addComponent(btnLogoutTranscript)
                .addGap(48, 48, 48))
        );
        navigateBackPanel1Layout.setVerticalGroup(
            navigateBackPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navigateBackPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(navigateBackPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBackTranscript)
                    .addComponent(btnLogoutTranscript)
                    .addComponent(lblManageCourses))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        studentSplitPane1.setTopComponent(navigateBackPanel1);

        studentWorkAreaPanel1.setBackground(new java.awt.Color(37, 150, 190));

        tblTranscripts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Student Major", "Current Semester", "Course ID", "Course Name", "Course Description", "Professor ID", "Professor Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tblTranscripts);

        lblCourseID.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblCourseID.setText("Course ID");

        lblCourseName.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblCourseName.setText("Course Name");

        lblCourseDescription.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblCourseDescription.setText("Course Description");

        txtGrade1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGrade1ActionPerformed(evt);
            }
        });

        lblProfessorIDCourse.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblProfessorIDCourse.setText("Professor ID");

        lblStudentID5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblStudentID5.setText("Student Major");

        txtProfessorName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProfessorNameActionPerformed(evt);
            }
        });

        lblCurrentSemester1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblCurrentSemester1.setText("Current Semester");

        lblProfessorName.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblProfessorName.setText("Professor Name");

        comboSemester1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Semester", "Fall 2022", "Winter 2022", "Spring 2023", "Summer 2023", "Fall 2023", "Winter 2023", "Spring 2024", "Summer 2024", "Fall 2024", "Winter 2024", " " }));

        btnUpdateCourse.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnUpdateCourse.setText("UPDATE");

        txtProfessorIDCourse.setEditable(false);
        txtProfessorIDCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProfessorIDCourseActionPerformed(evt);
            }
        });

        btnViewCourse.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnViewCourse.setText("VIEW");

        btnCreateCourse.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnCreateCourse.setText("SAVE");
        btnCreateCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateCourseActionPerformed(evt);
            }
        });

        btnDeleteCourse.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnDeleteCourse.setText("DELETE");

        javax.swing.GroupLayout studentWorkAreaPanel1Layout = new javax.swing.GroupLayout(studentWorkAreaPanel1);
        studentWorkAreaPanel1.setLayout(studentWorkAreaPanel1Layout);
        studentWorkAreaPanel1Layout.setHorizontalGroup(
            studentWorkAreaPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4)
            .addGroup(studentWorkAreaPanel1Layout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addGroup(studentWorkAreaPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, studentWorkAreaPanel1Layout.createSequentialGroup()
                        .addComponent(lblCourseID, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtCourseID, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, studentWorkAreaPanel1Layout.createSequentialGroup()
                        .addComponent(lblCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, studentWorkAreaPanel1Layout.createSequentialGroup()
                        .addComponent(lblProfessorIDCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(txtProfessorIDCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, studentWorkAreaPanel1Layout.createSequentialGroup()
                        .addComponent(lblProfessorName, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtProfessorName, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, studentWorkAreaPanel1Layout.createSequentialGroup()
                        .addGroup(studentWorkAreaPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblCourseDescription, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCurrentSemester1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(studentWorkAreaPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboSemester1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCourseDescription, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, studentWorkAreaPanel1Layout.createSequentialGroup()
                        .addComponent(lblStudentID5, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtGrade1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, studentWorkAreaPanel1Layout.createSequentialGroup()
                .addContainerGap(182, Short.MAX_VALUE)
                .addGroup(studentWorkAreaPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCreateCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(studentWorkAreaPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnViewCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(230, 230, 230))
        );
        studentWorkAreaPanel1Layout.setVerticalGroup(
            studentWorkAreaPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentWorkAreaPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(studentWorkAreaPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStudentID5)
                    .addComponent(txtGrade1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(studentWorkAreaPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(studentWorkAreaPanel1Layout.createSequentialGroup()
                        .addGroup(studentWorkAreaPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboSemester1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCurrentSemester1))
                        .addGap(18, 18, 18)
                        .addGroup(studentWorkAreaPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCourseID)
                            .addComponent(txtCourseID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(studentWorkAreaPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCourseName)
                            .addComponent(txtCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(studentWorkAreaPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCourseDescription)
                            .addComponent(txtCourseDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(studentWorkAreaPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblProfessorName)
                            .addComponent(txtProfessorName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41))
                    .addGroup(studentWorkAreaPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblProfessorIDCourse)
                        .addComponent(txtProfessorIDCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(studentWorkAreaPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCreateCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(studentWorkAreaPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdateCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45))
        );

        studentSplitPane1.setRightComponent(studentWorkAreaPanel1);

        javax.swing.GroupLayout coursesPanelLayout = new javax.swing.GroupLayout(coursesPanel);
        coursesPanel.setLayout(coursesPanelLayout);
        coursesPanelLayout.setHorizontalGroup(
            coursesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, coursesPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(studentSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 898, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        coursesPanelLayout.setVerticalGroup(
            coursesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(studentSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        rightPane.add(coursesPanel, "card3");

        DashboardPanel.setRightComponent(rightPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DashboardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1049, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DashboardPanel))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentsActionPerformed
        // TODO add your handling code here:
        workAreaPanel.setVisible(false);
        studentPanel.setVisible(true);
    }//GEN-LAST:event_btnStudentsActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void txtPhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneNumberActionPerformed

    private void txtStudentIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStudentIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStudentIDActionPerformed

    private void txtInstituteCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInstituteCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInstituteCodeActionPerformed

    private void txtPhoneNumberProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneNumberProfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneNumberProfActionPerformed

    private void txtProfessorIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProfessorIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProfessorIDActionPerformed

    private void txtInstituteCodeProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInstituteCodeProfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInstituteCodeProfActionPerformed

    private void txtProfessorPhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProfessorPhotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProfessorPhotoActionPerformed

    private void btnPhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPhotoActionPerformed
        // TODO add your handling code here:
        JFileChooser image = new JFileChooser();
        FileNameExtensionFilter nameFilter = new FileNameExtensionFilter("jpeg", "jpg", "png");
        image.addChoosableFileFilter(nameFilter);
        int dlgBox = image.showOpenDialog(null);

        if(dlgBox == JFileChooser.APPROVE_OPTION){
            File f = image.getSelectedFile();
            this.photoPath = f.getAbsolutePath();
            ImageIcon icon = new ImageIcon(photoPath);
            this.studentPhoto = icon;
        }

        if(studentPhoto !=null){
            Image resizedImage = studentPhoto.getImage().getScaledInstance(lblStudentPhoto.getWidth(), lblStudentPhoto.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon resizedIconPic = new ImageIcon(resizedImage);
            lblStudentPhoto.setIcon(resizedIconPic);
            JOptionPane.showMessageDialog(this, "Image Successfully Uploaded");
        }
    }//GEN-LAST:event_btnPhotoActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        String studentName = txtFirstName.getText();
        String studentEmail = txtEmailAddress.getText();
        String studentGender = "";
        if(btnMale.isSelected()){
            studentGender = "Male";
        } else if (btnFemale.isSelected()){
            studentGender = "Female";
        } else {
            studentGender = "Non Binary";
        } 
        String studentSSN = txtSSN.getText();
        Date dob = dateChooser.getDate();
        String gradYear = txtGradYear.getText();
        long studentPhone = Long.parseLong(txtPhoneNumber.getText());
        String studentPassword = String.valueOf(passwordFieldStudent.getPassword());
        String studentID = txtStudentID.getText();
        String instituteCode = txtInstituteCode.getText();
        String degreeLevel = comboDegreeLevel.getSelectedItem().toString();
        String major = txtStudentMajor.getText();
        
        Degree studentDegree = new Degree(degreeLevel, major);
        String currentSemester = comboSemester.getSelectedItem().toString();
        Community community = new Community("Westland", new City("Boston"));
        String photo = photoPath;
        
        
        
        List<String> personIdList = UniversityAdmin.personDirectoryRef.getPersonDirectory().stream().map(x -> x.getPersonId()).toList();
//        List<String> studentIdList = UniversityAdmin.studentDirectoryRef.getStudentDirectory().stream().map(x -> x.getStudentID()).toList();

        if(personIdList.contains(studentSSN)){
           JOptionPane.showMessageDialog(this, "SSN already exists. Please check"); 
        } else {
            Student student = new Student(studentName, studentGender, 
            studentSSN, dob,  studentPhone, studentEmail, 
            community, studentPassword, studentID, instituteCode,
            studentDegree, gradYear,  currentSemester, photo);
            
            UniversityAdmin.personDirectoryRef.getPersonDirectory().add(student);
            UniversityAdmin.studentDirectoryRef.getStudentDirectory().add(student);
            JOptionPane.showMessageDialog(this, "New Student Added Successfully!"); 
            
            txtFirstName.setText("");
            txtLastName.setText("");
            txtEmailAddress.setText("");
            genderButtonGroup.clearSelection();
            txtSSN.setText("");
            dateChooser.setCalendar(null);
            txtGradYear.setText("");
            txtPhoneNumber.setText("");
            passwordFieldStudent.setText("");
            txtStudentID.setText("");
            txtInstituteCode.setText("");
            comboDegreeLevel.removeAllItems();
            comboSemester.removeAllItems();
            txtStudentMajor.setText("");
//            lblStudentPhoto
            populateTable();

        }
    }//GEN-LAST:event_btnCreateActionPerformed

    private void txtStudentMajorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStudentMajorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStudentMajorActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        
         int selected = tblStudents.getSelectedRow();
        
         if (selected < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row to update!");
            return;
        }
         
        Student student = UniversityAdmin.studentDirectoryRef.getStudentDirectory().get(selected);
        
        txtFirstName.setText(student.getPersonName());
        txtEmailAddress.setText(student.getPersonEmailAddress());
        if(student.getPersonGender().equals("Female")){
            btnFemale.setSelected(true);
            btnMale.setSelected(false);
            btnNonBinary.setSelected(false);
        } else if (student.getPersonGender().equals("Male")){
        btnMale.setSelected(true);
        btnFemale.setSelected(false);
            btnNonBinary.setSelected(false);
    } else {
            btnNonBinary.setSelected(true);
            btnMale.setSelected(false);
            btnFemale.setSelected(false);
        }
        txtSSN.setText(student.getPersonId());
        dateChooser.setDate(student.getDateOfBirth());
        txtGradYear.setText(student.getGraduationYear());
//      m txtPhoneNumber.setText(student.getPersonPhoneNumber());
        passwordFieldStudent.setText(String.valueOf(student.getUserPassword()));
        txtStudentID.setText(student.getStudentID());
        txtInstituteCode.setText(student.getInstituteCode());
        comboDegreeLevel.setSelectedItem(student.getStudentDegree().getDegreeLevel());
        txtStudentMajor.setText(student.getStudentDegree().getMajor());
        comboSemester.setSelectedItem(student.getCurrentSemester());
        
//        Community community = new Community("Westland", new City("Boston"));
        String photo = student.getPhoto();
        ImageIcon icon = new ImageIcon(photoPath);
        // Resize image to fit jLabel
        Image image = icon.getImage().getScaledInstance(134,138,4);
        // Set jLabel icon property to image
        lblStudentPhoto.setIcon(new ImageIcon(image));
        
    }//GEN-LAST:event_btnViewActionPerformed

    private void txtGrade1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGrade1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGrade1ActionPerformed

    private void txtProfessorNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProfessorNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProfessorNameActionPerformed

    private void txtProfessorIDCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProfessorIDCourseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProfessorIDCourseActionPerformed

    private void btnCreateCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateCourseActionPerformed
        // TODO add your handling code here:
        String 
        
    }//GEN-LAST:event_btnCreateCourseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane DashboardPanel;
    private javax.swing.JPasswordField PasswordProfessor;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBackFaculty;
    private javax.swing.JButton btnBackTranscript;
    private javax.swing.JButton btnCourses;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnCreateCourse;
    private javax.swing.JButton btnCreateProf;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDeleteCourse;
    private javax.swing.JButton btnDeleteProf;
    private javax.swing.JButton btnDormitories;
    private javax.swing.JButton btnFaculty;
    private javax.swing.JRadioButton btnFemale;
    private javax.swing.JRadioButton btnFemale1;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnLogoutFaculty;
    private javax.swing.JButton btnLogoutTranscript;
    private javax.swing.JRadioButton btnMale;
    private javax.swing.JRadioButton btnMale1;
    private javax.swing.JButton btnMealOrders;
    private javax.swing.JRadioButton btnNonBinary;
    private javax.swing.JRadioButton btnNonBinary1;
    private javax.swing.JButton btnPhoto;
    private javax.swing.JButton btnReports;
    private javax.swing.JButton btnStudents;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnUpdateCourse;
    private javax.swing.JButton btnUpdateProf;
    private javax.swing.JButton btnView;
    private javax.swing.JButton btnViewCourse;
    private javax.swing.JButton btnViewProf;
    private javax.swing.JComboBox<String> comboDegreeLevel;
    private javax.swing.JComboBox<String> comboSemester;
    private javax.swing.JComboBox<String> comboSemester1;
    private javax.swing.JPanel coursesPanel;
    private com.toedter.calendar.JDateChooser dateChooser;
    private com.toedter.calendar.JDateChooser dateOfBirthProf;
    private javax.swing.JPanel facultyPanel;
    private javax.swing.JSplitPane facultySplitPane;
    private javax.swing.ButtonGroup genderButtonGroup;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblCourseDescription;
    private javax.swing.JLabel lblCourseID;
    private javax.swing.JLabel lblCourseName;
    private javax.swing.JLabel lblCurrentSemester;
    private javax.swing.JLabel lblCurrentSemester1;
    private javax.swing.JLabel lblDateofBirth;
    private javax.swing.JLabel lblDateofBirth1;
    private javax.swing.JLabel lblDobProf;
    private javax.swing.JLabel lblEmailAddress;
    private javax.swing.JLabel lblEmailAddressProf;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblFirstNameProf;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblGender1;
    private javax.swing.JLabel lblGraduationYear;
    private javax.swing.JLabel lblInstituteCodeProf;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblLastNameProf;
    private javax.swing.JLabel lblManageCourses;
    private javax.swing.JLabel lblManageFaculty;
    private javax.swing.JLabel lblManageStudents;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPasswordProfessor;
    private javax.swing.JLabel lblPhoneNumberProf;
    private javax.swing.JLabel lblPhoto;
    private javax.swing.JLabel lblPhotoProfessor;
    private javax.swing.JLabel lblProfessorID;
    private javax.swing.JLabel lblProfessorIDCourse;
    private javax.swing.JLabel lblProfessorName;
    private javax.swing.JLabel lblProfessorStartDate;
    private javax.swing.JLabel lblSSN;
    private javax.swing.JLabel lblSSNProf;
    private javax.swing.JLabel lblStudentDegreeLevel;
    private javax.swing.JLabel lblStudentID;
    private javax.swing.JLabel lblStudentID1;
    private javax.swing.JLabel lblStudentID5;
    private javax.swing.JLabel lblStudentMajor;
    private javax.swing.JLabel lblStudentPhoto;
    private javax.swing.JPanel leftPane;
    private javax.swing.JPanel navigateBackPanel;
    private javax.swing.JPanel navigateBackPanel1;
    private javax.swing.JPanel navigateBackPanelFaculty;
    private javax.swing.JPasswordField passwordFieldStudent;
    private javax.swing.JPanel professorWorkAreaPanel;
    private javax.swing.JLayeredPane rightPane;
    private com.toedter.calendar.JDateChooser startDateChooser;
    private javax.swing.JPanel studentPanel;
    private javax.swing.JSplitPane studentSplitPane;
    private javax.swing.JSplitPane studentSplitPane1;
    private javax.swing.JPanel studentWorkAreaPanel;
    private javax.swing.JPanel studentWorkAreaPanel1;
    private javax.swing.JTable tblStudents;
    private javax.swing.JTable tblStudents1;
    private javax.swing.JTable tblTranscripts;
    private javax.swing.JTextField txtCourseDescription;
    private javax.swing.JTextField txtCourseID;
    private javax.swing.JTextField txtCourseName;
    private javax.swing.JTextField txtEmailAddress;
    private javax.swing.JTextField txtEmailAddressProf;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtFirstNameProf;
    private javax.swing.JTextField txtGradYear;
    private javax.swing.JTextField txtGrade1;
    private javax.swing.JTextField txtInstituteCode;
    private javax.swing.JTextField txtInstituteCodeProf;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtLastNameProf;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JTextField txtPhoneNumberProf;
    private javax.swing.JTextField txtProfessorID;
    private javax.swing.JTextField txtProfessorIDCourse;
    private javax.swing.JTextField txtProfessorName;
    private javax.swing.JTextField txtProfessorPhoto;
    private javax.swing.JTextField txtSSN;
    private javax.swing.JTextField txtSSNProf;
    private javax.swing.JTextField txtStudentID;
    private javax.swing.JTextField txtStudentMajor;
    private javax.swing.JLabel workAreaPane;
    private javax.swing.JPanel workAreaPanel;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
         DefaultTableModel model = (DefaultTableModel) tblStudents.getModel();
         model.setRowCount(0);
         for(Student student: UniversityAdmin.studentDirectoryRef.getStudentDirectory()){
             Object[] rowData = new Object[10];
             rowData[0] = student.getPersonName();
             rowData[1] = student.getStudentID();
             rowData[2] = student.getPersonEmailAddress();
             rowData[3] = student.getPersonGender();
             rowData[4] = student.getPersonPhoneNumber();
             rowData[5] = student.getInstituteCode();
             rowData[6] = student.getStudentDegree().getDegreeLevel();
             rowData[7] = student.getStudentDegree().getMajor();
             rowData[8] = student.getCurrentSemester();
             rowData[9] = student.getGraduationYear();
             model.addRow(rowData);
         }
    }
}
